import { FC, ReactNode } from "react";
import { cookies } from "next/headers";
import { Metadata } from "next";
import { useTranslation } from "../i18n";
import { dir } from "i18next";

import "../globals.css";
import Providers from "@/components/Providers";
import Header from "@/components/MainLayout/Header";
import Footer from "@/components/MainLayout/Footer";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout:FC<{
  children: ReactNode;
}> = async ({
  children,
}) => {
  const cookieStore = await cookies();
  const cookieLocale = cookieStore.get('locale')?.value || 'en';

  // eslint-disable-next-line react-hooks/rules-of-hooks
  await useTranslation( cookieLocale, [ 'common', 'landing' ] );

  return (
    <html lang="en" dir={dir(cookieLocale)}>
      <body>
        <Providers
          locale={ cookieLocale }
        >
          <Header />
            {/* <Suspense fallback={ <div>Loading...</div> }> */}
          { children }
            {/* </Suspense> */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
