import { FC, ReactNode } from "react";
import { cookies } from "next/headers";
import { Metadata } from "next";
import { dir } from "i18next";
import { getServerSession } from "next-auth";
import { authConfig } from "@/lib/auth/authConfig";
import { fetchFromServer } from "@/utils/fetchFromServer";

import "../globals.css";
import Providers from "@/components/Providers";
import Header from "@/components/MainLayout/Header";
import Footer from "@/components/MainLayout/Footer";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout:FC<{
  children: ReactNode;
}> = async ({
  children,
}) => {
  const cookieStore = await cookies();
  const cookieLocale = cookieStore.get('locale')?.value || 'en';
  const session = await getServerSession(authConfig);
  const token = session?.user?.token?.accessToken;
  let me = null;
  let documents = null;
  try {
    if (token) {
      const resp = await fetchFromServer(`/api/v1/user/me`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
      });
      me = resp.user;
      documents = resp.documents;
      console.log(me);
    }
  } catch (error) {
    console.error('Error fetching user profile:', error);
  }

  return (
    <html lang="en" dir={dir(cookieLocale)}>
      <body>
        <Providers
          locale={ cookieLocale }
          token={ token || '' }
          session={ session }
          me={ me }
          documents={ documents }
        >
          <Header />
            {/* <Suspense fallback={ <div>Loading...</div> }> */}
          { children }
            {/* </Suspense> */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
