import { FC, ReactNode } from "react";
import { cookies } from "next/headers";
import { Metadata } from "next";
import { dir } from "i18next";

import "./globals.css";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout:FC<{
  children: ReactNode;
}> = async ({
  children,
}) => {
  const cookieStore = await cookies();
  const cookieLocale = cookieStore.get('locale')?.value || 'en';
  return (
    <html lang="en" dir={dir(cookieLocale)}>
      <body>
        { children }
      </body>
    </html>
  );
}

export default RootLayout;
